# Business Problem - Predict the Price of Bangalore House
Using Linear Regression - Supervised Machine Learning Algorithm

### Load Libraries

### Load Data

In [28]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\DELL\OneDrive\Desktop\Python_Test\House Price India_regression.csv")
df

id   Date  number of bedrooms  number of bathrooms  \
0      6762810145  42491                   5                 2.50   
1      6762810635  42491                   4                 2.50   
2      6762810998  42491                   5                 2.75   
3      6762812605  42491                   4                 2.50   
4      6762812919  42491                   3                 2.00   
...           ...    ...                 ...                  ...   
14615  6762830250  42734                   2                 1.50   
14616  6762830339  42734                   3                 2.00   
14617  6762830618  42734                   2                 1.00   
14618  6762830709  42734                   4                 1.00   
14619  6762831463  42734                   3                 1.00   

       living area  lot area  number of floors  waterfront present  \
0             3650      9050               2.0                   0   
1             2920      4000               1.5                   0   
2             2910      9480               1.5                   0   
3             3310     42998               2.0                   0   
4             2710      4500               1.5                   0   
...            ...       ...               ...                 ...   
14615         1556     20000               1.0                   0   
14616         1680      7000               1.5                   0   
14617         1070      6120               1.0                   0   
14618         1030      6621               1.0                   0   
14619          900      4770               1.0                   0   

       number of views  condition of the house  ...  Built Year  \
0                    4                       5  ...        1921   
1                    0                       5  ...        1909   
2                    0                       3  ...        1939   
3                    0                       3  ...        2001   
4                    0                       4  ...        1929   
...                ...                     ...  ...         ...   
14615                0                       4  ...        1957   
14616                0                       4  ...        1968   
14617                0                       3  ...        1962   
14618                0                       4  ...        1955   
14619                0                       3  ...        1969   

       Renovation Year  Postal Code  Lattitude  Longitude  living_area_renov  \
0                    0       122003    52.8645   -114.557               2880   
1                    0       122004    52.8878   -114.470               2470   
2                    0       122004    52.8852   -114.468               2940   
3                    0       122005    52.9532   -114.321               3350   
4                    0       122006    52.9047   -114.485               2060   
...                ...          ...        ...        ...                ...   
14615                0       122066    52.6191   -114.472               2250   
14616                0       122072    52.5075   -114.393               1540   
14617                0       122056    52.7289   -114.507               1130   
14618                0       122042    52.7157   -114.411               1420   
14619             2009       122018    52.5338   -114.552                900   

       lot_area_renov  Number of schools nearby  Distance from the airport  \
0                5400                         2                         58   
1                4000                         2                         51   
2                6600                         1                         53   
3               42847                         3                         76   
4                4500                         1                         51   
...               ...                       ...                        ...   
14615           17286            

In [4]:
df.head()

id   Date  number of bedrooms  number of bathrooms  living area  \
0  6762810145  42491                   5                 2.50         3650   
1  6762810635  42491                   4                 2.50         2920   
2  6762810998  42491                   5                 2.75         2910   
3  6762812605  42491                   4                 2.50         3310   
4  6762812919  42491                   3                 2.00         2710   

   lot area  number of floors  waterfront present  number of views  \
0      9050               2.0                   0                4   
1      4000               1.5                   0                0   
2      9480               1.5                   0                0   
3     42998               2.0                   0                0   
4      4500               1.5                   0                0   

   condition of the house  ...  Built Year  Renovation Year  Postal Code  \
0                       5  ...        1921                0       122003   
1                       5  ...        1909                0       122004   
2                       3  ...        1939                0       122004   
3                       3  ...        2001                0       122005   
4                       4  ...        1929                0       122006   

   Lattitude  Longitude  living_area_renov  lot_area_renov  \
0    52.8645   -114.557               2880            5400   
1    52.8878   -114.470               2470            4000   
2    52.8852   -114.468               2940            6600   
3    52.9532   -114.321               3350           42847   
4    52.9047   -114.485               2060            4500   

   Number of schools nearby  Distance from the airport    Price  
0                         2                         58  2380000  
1                         2                         51  1400000  
2                         1                         53  1200000  
3                         3                         76   838000  
4                         1                         51   805000  

[5 rows x 23 columns]

### Split Data

In [5]:
X = df.drop('Price', axis=1)
y = df['Price']
print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (14620, 22)
Shape of y =  (14620,)


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (11696, 22)
Shape of y_train =  (11696,)
Shape of X_test =  (2924, 22)
Shape of y_test =  (2924,)


### Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

## Linear Regression - ML Model Training

In [8]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [9]:
lr.coef_

array([-141114.48100664,     674.15952096,  -38069.35640934,
         22143.82342769,   80550.59979666,   -7272.23447569,
        -14511.27322352,   51837.71988274,   29333.78483841,
          7936.72288853,   62735.74054644,   78952.3485323 ,
         20754.04648187,  -46639.72001207,    7025.50253629,
         21306.07813908,   26428.71451126,  -15482.60774833,
        -14651.99102213,  -10193.25102539,    1206.75663591,
          -862.44771725])

In [10]:
lr.intercept_

541529.9142387052

## Predict the value of Home and Test

In [11]:
X_test[0, :]

array([ 0.23992348,  0.08364648,  0.68924324,  0.15179725,  0.14714094,
       -0.06311312, -0.92885971, -0.0875659 , -0.30560125,  0.85704634,
        0.26511308, -0.0887838 ,  0.46701128,  0.34151117, -0.21936179,
       -0.95142606, -0.61982403,  0.51411488,  0.21515541,  0.00256414,
       -0.01285327,  1.45695716])

In [12]:
lr.predict([X_test[0, :]])

array([456723.47283101])

In [13]:
lr.predict(X_test)

array([456723.47283101, 262754.03881636, 195658.80849231, ...,
       638161.48812197, 711352.18582869, 406148.8172573 ])

In [14]:
y_test

8066      415000
4221      240000
7303      260000
12344    1330000
6368      582000
          ...   
8057      483000
8663      368000
10528     559000
7254      482000
11457     473000
Name: Price, Length: 2924, dtype: int64

In [15]:
lr.score(X_test, y_test)

0.7350670175526429

impliment ridge and lasso regression

In [16]:
from sklearn.linear_model import Ridge ,  Lasso

In [17]:
rd=Ridge()
rd.fit(X_train,y_train)
rd.score(X_test,y_test)


0.7350758518547853

In [18]:
rd=Lasso()


rd.fit(X_train,y_train)

rd.score(X_test,y_test)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.291e+13, tolerance: 1.649e+11
  model = cd_fast.enet_coordinate_descent(


0.7350676340680905

In [19]:
rd2=Ridge(alpha=2)


rd2.fit(X_train,y_train)

rd2.score(X_test,y_test)

0.7350846720361859

In [20]:
rd3=Lasso(alpha=2)


rd3.fit(X_train,y_train)

rd3.score(X_test,y_test)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.292e+13, tolerance: 1.649e+11
  model = cd_fast.enet_coordinate_descent(


0.7350682498357449

model evaluation

root mean square error

In [22]:
y_pred=lr.predict(X_test)
y_pred

array([456723.47283101, 262754.03881636, 195658.80849231, ...,
       638161.48812197, 711352.18582869, 406148.8172573 ])

In [23]:
y_test

8066      415000
4221      240000
7303      260000
12344    1330000
6368      582000
          ...   
8057      483000
8663      368000
10528     559000
7254      482000
11457     473000
Name: Price, Length: 2924, dtype: int64

In [24]:
from sklearn.metrics import mean_squared_error

In [29]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print(mse)
print (rmse)


29506936373.75736
171775.83175102764
